# Generated by Django 6.0.5 on 2026-05-17 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='fecha_asignacion',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='fecha_devolucion',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_entrega',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
